# Generated by Django 4.2.17 on 2025-01-14 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idcard', models.CharField(blank=True, max_length=20, unique=True, verbose_name='身份证号')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='姓名')),
                ('mobile', models.CharField(blank=True, max_length=11, verbose_name='手机号')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10, verbose_name='性别')),
                ('password', models.CharField(max_length=128, verbose_name='密码')),
            ],
        ),
    ]
