# Generated by Django 4.2.17 on 2025-01-11 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idcard', models.CharField(blank=True, max_length=18, null=True, unique=True, verbose_name='身份证号')),
                ('email', models.EmailField(max_length=50, unique=True, verbose_name='邮箱')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='生日')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女')], default='female', max_length=10, verbose_name='性别')),
                ('mobile', models.CharField(blank=True, max_length=11, null=True, verbose_name='手机号')),
            ],
        ),
    ]
