# Generated by Django 4.2.17 on 2025-01-16 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idcard', models.CharField(blank=True, max_length=20, unique=True, verbose_name='身份证号')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='姓名')),
                ('gender', models.CharField(choices=[('M', '男'), ('F', '女')], max_length=10, verbose_name='性别')),
                ('mobile', models.CharField(blank=True, max_length=11, unique=True, verbose_name='手机号')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='邮箱')),
                ('password', models.CharField(max_length=128, verbose_name='密码')),
                ('avatar', models.CharField(default='static/images/default_user.jpg', max_length=100, verbose_name='头像')),
            ],
            options={
                'verbose_name': '患者',
                'verbose_name_plural': '患者',
            },
        ),
    ]
