# Generated by Django 4.2.17 on 2025-01-20 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docID', models.CharField(blank=True, max_length=20, unique=True, verbose_name='医生编号')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('title', models.CharField(max_length=50, verbose_name='职称')),
                ('gender', models.CharField(choices=[('M', '男'), ('F', '女')], max_length=10, verbose_name='性别')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='邮箱')),
                ('intro', models.TextField(blank=True, max_length=500, verbose_name='简介')),
                ('avatar', models.CharField(default='static/images/default_doctor.jpg', max_length=100, verbose_name='头像')),
            ],
            options={
                'verbose_name': '医生',
                'verbose_name_plural': '医生',
            },
        ),
    ]
