# Generated by Django 4.2.17 on 2025-01-27 03:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='出生日期'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='password',
            field=models.CharField(default='password', max_length=128, verbose_name='密码'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='patient',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='patient',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='avatar',
            field=models.ImageField(default='static/images/default_doctor.jpg', upload_to='avatars/doctors/', verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='docID',
            field=models.CharField(max_length=20, unique=True, verbose_name='医生编号'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='avatar',
            field=models.ImageField(default='static/images/default_user.jpg', upload_to='avatars/patients/', verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='idcard',
            field=models.CharField(max_length=20, unique=True, verbose_name='身份证号'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='mobile',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='手机号必须为11位数字', regex='^[0-9]{11}$')], verbose_name='手机号'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=models.CharField(max_length=50, verbose_name='姓名'),
        ),
    ]
