# Generated by Django 4.2.17 on 2025-02-13 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_doctor_birthday_doctor_created_at_doctor_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='avatar',
            field=models.ImageField(default='avatars/doctors/default_doctor.jpg', upload_to='avatars/doctors/', verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='avatar',
            field=models.ImageField(default='avatars/patients/default_user.jpg', upload_to='avatars/patients/', verbose_name='头像'),
        ),
    ]
