# Generated by Django 4.2.17 on 2025-02-21 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_doctor_avatar_alter_patient_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('confirmed', '已确认'), ('cancelled', '已取消'), ('completed', '已完成')], default='pending', max_length=20, verbose_name='状态')),
                ('notes', models.TextField(blank=True, max_length=500, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '预约记录',
                'verbose_name_plural': '预约记录',
            },
        ),
        migrations.AlterField(
            model_name='patient',
            name='avatar',
            field=models.ImageField(default='avatars/patients/default_patient.jpg', upload_to='avatars/patients/', verbose_name='头像'),
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.TextField(blank=True, max_length=500, verbose_name='诊断结果')),
                ('treatment', models.TextField(blank=True, max_length=500, verbose_name='治疗方案')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.appointment', verbose_name='预约记录')),
            ],
            options={
                'verbose_name': '诊疗记录',
                'verbose_name_plural': '诊疗记录',
            },
        ),
        migrations.CreateModel(
            name='DoctorSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('start_time', models.TimeField(verbose_name='开始时间')),
                ('end_time', models.TimeField(verbose_name='结束时间')),
                ('is_available', models.BooleanField(default=True, verbose_name='是否可预约')),
                ('max_patients', models.IntegerField(default=1, verbose_name='最大患者数')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.doctor', verbose_name='医生')),
            ],
            options={
                'verbose_name': '医生排班',
                'verbose_name_plural': '医生排班',
                'unique_together': {('doctor', 'date', 'start_time', 'end_time')},
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor_schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.doctorschedule', verbose_name='医生排班'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.patient', verbose_name='患者'),
        ),
    ]
