# Generated by Django 4.2.17 on 2025-03-06 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_appointment_alter_patient_avatar_medicalrecord_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorschedule',
            name='current_patients',
            field=models.IntegerField(default=0, verbose_name='当前患者数'),
        ),
    ]
