# Generated by Django 4.2.17 on 2025-03-25 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_medicalrecord_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='ai_analysis',
            field=models.JSONField(null=True, verbose_name='AI分析结果'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='appointment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.appointment', verbose_name='预约记录'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='consultations/%Y/%m/%d/'),
        ),
    ]
