# Generated by Django 4.2.17 on 2025-03-25 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_medicalrecord_ai_analysis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='ai_analysis',
            field=models.JSONField(blank=True, null=True, verbose_name='AI分析结果'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='consultation_images/'),
        ),
    ]
