# Generated by Django 4.2.17 on 2025-03-25 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_medicalrecord_ai_analysis_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalrecord',
            name='ai_analysis',
        ),
    ]
