# Generated by Django 4.2.17 on 2025-03-25 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_remove_medicalrecord_ai_analysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='ai_diagnosis',
            field=models.TextField(blank=True, max_length=500, verbose_name='AI诊断结果'),
        ),
    ]
