# Generated by Django 4.2.17 on 2025-03-27 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_medicalrecord_ai_diagnosis'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorschedule',
            name='is_expired',
            field=models.BooleanField(default=False, verbose_name='是否过期'),
        ),
    ]
